# -*- coding: utf-8 -*-
"""image-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/mpomirski/b6487ad3d75b864b4d53e027a35e9639/image-classification.ipynb
"""

!pip install imageai

from imageai.Detection import ObjectDetection

detector = ObjectDetection()

path_model = "./Models/tiny-yolov3.pt"
path_input = "./Input/image.jpg"
path_output = "./Output/newimage.jpg"

detector.setModelTypeAsTinyYOLOv3()
detector.setModelPath(path_model)
detector.loadModel()

recognition = detector.detectObjectsFromImage(
    input_image = path_input,
    output_image_path = path_output
)

for eachItem in recognition:
    print(eachItem["name"] , " : ", eachItem["percentage_probability"])